name = "AdditiveClosuresForCAP"
uuid = "bbee75d5-3cb4-4478-8ae7-eddc7864e69e"
authors = [
	"Sebastian Posur <sebastian.posur@uni-muenster.de>",
	"Martin Bies <martin.bies@rptu.de>",
	"Mohamed Barakat <mohamed.barakat@uni-siegen.de>",
	"Kamal Saleh <kamal.saleh@uni-siegen.de>",
	"Fabian Zickgraf <f.zickgraf@dashdos.com>"
]

# Transpiled from GAP's AdditiveClosuresForCAP v2026.05-01
version = "0.2.1"

[deps]
CAP = "d64df2ee-d2bb-46f4-8cbc-f03bb858f8cb"
MatricesForHomalg = "29b9b1b6-efa6-450e-8188-a5a2c25df071"
LinearAlgebraForCAP = "3dc4824f-14ac-4ab7-8a60-75dbcd4a9d60"
MonoidalCategories = "bfd98c86-782f-4b94-909f-74167f1eb613"

[weakdeps]

[extensions]

[compat]
julia = "1.11"
CAP = "0.7"
MatricesForHomalg = "~0.1.1"
LinearAlgebraForCAP = "0.2"
MonoidalCategories = "~0.2.15"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[targets]
test = ["Test", "Documenter"]
